/**
 * ============================================================
 * CV DOWNLOAD — Generate Real CV File from Applicant Data
 * ============================================================
 * Creates a downloadable text file from the applicant's profile
 * data. In production this would link to an uploaded PDF.
 * ============================================================
 */

export interface CVData {
  firstName: string;
  lastName: string;
  levavCode: string;
  wriScore: number;
  goldKeyTier: string;
  profession: string;
  city: string;
  email: string;
  phone: string;
  linkedIn?: string | null;
  education: string;
  experience: string;
  skills: string[];
  certifications: string[];
  languages: string[];
  coverLetter: string;
  wriComponents?: {
    culture: number;
    criticalThinking: number;
    reliability: number;
    communication: number;
    learning: number;
    leadership: number;
    impact: number;
  };
  levav28Progress?: number;
  levav28AvgScore?: number;
  references?: { name: string; role: string; contact: string }[];
}

export function downloadCV(data: CVData): void {
  const fullName = `${data.firstName || ""} ${data.lastName || ""}`.trim();
  const lines: string[] = [];

  lines.push("=".repeat(60));
  lines.push("  LEVAV ID™ PORTFOLIO / CV");
  lines.push("=".repeat(60));
  lines.push("");
  lines.push(`NAME:       ${fullName}`);
  lines.push(`LEVAV ID:   ${data.levavCode || "N/A"}`);
  lines.push(`WRI™:        ${(data.wriScore || 0).toFixed(1)} (${data.goldKeyTier || "N/A"} Tier)`);
  lines.push(`PROFESSION: ${data.profession || "N/A"}`);
  lines.push(`LOCATION:   ${data.city || "N/A"}`);
  lines.push("");
  lines.push("-".repeat(60));
  lines.push("CONTACT");
  lines.push("-".repeat(60));
  lines.push(`Email:  ${data.email || "N/A"}`);
  lines.push(`Phone:  ${data.phone || "N/A"}`);
  if (data.linkedIn) lines.push(`LinkedIn: ${data.linkedIn}`);
  lines.push("");
  lines.push("-".repeat(60));
  lines.push("EDUCATION");
  lines.push("-".repeat(60));
  lines.push(data.education || "Not provided");
  lines.push("");
  lines.push("-".repeat(60));
  lines.push("EXPERIENCE");
  lines.push("-".repeat(60));
  lines.push(data.experience || "Not provided");
  lines.push("");

  if (data.skills?.length) {
    lines.push("-".repeat(60));
    lines.push("SKILLS");
    lines.push("-".repeat(60));
    data.skills.forEach((s) => lines.push(`  • ${s}`));
    lines.push("");
  }

  if (data.certifications?.length) {
    lines.push("-".repeat(60));
    lines.push("CERTIFICATIONS");
    lines.push("-".repeat(60));
    data.certifications.forEach((c) => lines.push(`  ✓ ${c}`));
    lines.push("");
  }

  if (data.languages?.length) {
    lines.push("-".repeat(60));
    lines.push("LANGUAGES");
    lines.push("-".repeat(60));
    data.languages.forEach((l) => lines.push(`  • ${l}`));
    lines.push("");
  }

  if (data.wriComponents) {
    lines.push("-".repeat(60));
    lines.push("WORKFORCE READINESS INDEX™ (WRI™)");
    lines.push("-".repeat(60));
    lines.push(`  Culture Fit:        ${data.wriComponents.culture}/100`);
    lines.push(`  Critical Thinking:  ${data.wriComponents.criticalThinking}/100`);
    lines.push(`  Reliability:        ${data.wriComponents.reliability}/100`);
    lines.push(`  Communication:      ${data.wriComponents.communication}/100`);
    lines.push(`  Learning Agility:   ${data.wriComponents.learning}/100`);
    lines.push(`  Leadership:         ${data.wriComponents.leadership}/100`);
    lines.push(`  Impact:             ${data.wriComponents.impact}/100`);
    lines.push(`  OVERALL:            ${(data.wriScore || 0).toFixed(1)}/100 (${data.goldKeyTier} Tier)`);
    lines.push("");
  }

  if (data.levav28Progress !== undefined) {
    lines.push("-".repeat(60));
    lines.push("LEVAV 28™ CRUCIBLE");
    lines.push("-".repeat(60));
    lines.push(`  Progress: ${data.levav28Progress}/28 days`);
    lines.push(`  Average Score: ${(data.levav28AvgScore || 0).toFixed(1)}%`);
    lines.push("");
  }

  if (data.references?.length) {
    lines.push("-".repeat(60));
    lines.push("REFERENCES");
    lines.push("-".repeat(60));
    data.references.forEach((r) => {
      lines.push(`  ${r.name}`);
      lines.push(`    ${r.role}`);
      lines.push(`    ${r.contact}`);
      lines.push("");
    });
  }

  if (data.coverLetter) {
    lines.push("-".repeat(60));
    lines.push("COVER LETTER");
    lines.push("-".repeat(60));
    lines.push("");
    lines.push(data.coverLetter);
    lines.push("");
  }

  lines.push("=".repeat(60));
  lines.push("  Generated by Levav™ Talent Afrika");
  lines.push("  Africa's Workforce Intelligence Ecosystem");
  lines.push("=".repeat(60));

  const blob = new Blob([lines.join("\n")], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${fullName.replace(/\s+/g, "_")}_Levav_CV.txt`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
