/**
 * ============================================================
 * LEVAV TALENT AFRIKA — PHASE 1: CORE DATABASE INFRASTRUCTURE
 * ============================================================
 * Document: Levav Ecosystem Complete Core Specification v1.0.0
 * Build Methodology: Database Schemas & API Contracts First
 *
 * System Token Rules (Codebase):
 *   - All table names, columns, enums: lowercase, no special chars
 *   - FK columns referencing serial() PK: bigint("col", { mode: "number", unsigned: true })
 *
 * Schema Sections:
 *   1. Core Identity (users + levav_profiles + professions)
 *   2. WRI Analytics (wri_analytics + wri_component_scores)
 *   3. Levav 28 Onboarding (levav_code_acceptances + levav_28_sessions + levav_28_responses)
 *   4. Professional Data (skills_inventory + experience_history + education_history)
 *   5. Creator Studio (creator_studio_courses + course_lessons + course_enrollments + course_progress)
 *   6. QuickWork (quickwork_shifts + quickwork_applications)
 *   7. Impact (impact_partners + impact_opportunities + volunteer_ledger)
 *   8. Employer B2B (employer_profiles + job_postings + job_applications)
 *   9. Financial (transactions_wallet)
 *   10. System (notifications)
 * ============================================================
 */

import {
  mysqlTable,
  mysqlEnum,
  serial,
  bigint,
  varchar,
  text,
  timestamp,
  int,
  decimal,
  boolean,
  json,
  date,
  index,
  uniqueIndex,
} from "drizzle-orm/mysql-core";

/* ============================================================
   SECTION 1: CORE IDENTITY
   ============================================================ */

/**
 * users — Base identity table (auto-generated by auth init)
 * Extended with additional roles for the Levav ecosystem.
 */
export const users = mysqlTable(
  "users",
  {
    id: serial("id").primaryKey(),
    unionId: varchar("union_id", { length: 255 }).unique(),
    name: varchar("name", { length: 255 }),
    email: varchar("email", { length: 320 }),
    avatar: text("avatar"),
    passwordHash: varchar("password_hash", { length: 255 }),
    loginType: mysqlEnum("login_type", ["oauth", "local"]).default("oauth").notNull(),
    emailVerified: boolean("email_verified").default(false).notNull(),
    // Roles: admin (system), talent (job seeker), employer (B2B buyer), creator (content producer)
    role: mysqlEnum("role", ["user", "admin", "talent", "employer", "creator"])
      .default("user")
      .notNull(),
    // Account status for operational gating
    accountStatus: mysqlEnum("account_status", ["active", "suspended", "pending_verification"])
      .default("active")
      .notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .defaultNow()
      .notNull()
      .$onUpdate(() => new Date()),
    lastSignInAt: timestamp("last_sign_in_at").defaultNow().notNull(),
  },
  (table) => ({
    unionIdIdx: uniqueIndex("users_union_id_idx").on(table.unionId),
    roleIdx: index("users_role_idx").on(table.role),
    emailIdx: index("users_email_idx").on(table.email),
  })
);

export type User = typeof users.$inferSelect;
export type InsertUser = typeof users.$inferInsert;

/**
 * professions — Curated profession and specialty categories.
 * When a user selects "Other", custom_profession_text is stored on levav_profiles.
 */
export const professions = mysqlTable(
  "professions",
  {
    id: serial("id").primaryKey(),
    name: varchar("name", { length: 255 }).notNull(),
    category: varchar("category", { length: 255 }).notNull(), // e.g. "technology", "healthcare", "trades"
    description: text("description"),
    isActive: boolean("is_active").default(true).notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => ({
    categoryIdx: index("professions_category_idx").on(table.category),
    nameIdx: index("professions_name_idx").on(table.name),
  })
);

export type Profession = typeof professions.$inferSelect;
export type InsertProfession = typeof professions.$inferInsert;

/**
 * levav_profiles — The Levav ID talent portfolio (1:1 with users).
 * This is the central identity record for every talent user.
 */
export const levavProfiles = mysqlTable(
  "levav_profiles",
  {
    id: serial("id").primaryKey(),
    // FK to users (1:1 — each user has exactly one Levav profile)
    userId: bigint("user_id", { mode: "number", unsigned: true })
      .notNull()
      .unique(),
    // Public-facing Levav identifier code
    levavCode: varchar("levav_code", { length: 50 }).notNull().unique(),
    // Professional identity
    professionId: bigint("profession_id", { mode: "number", unsigned: true }),
    customProfessionText: varchar("custom_profession_text", { length: 255 }),
    // Personal details
    firstName: varchar("first_name", { length: 255 }),
    lastName: varchar("last_name", { length: 255 }),
    phone: varchar("phone", { length: 50 }),
    // Location (Zambia-focused initial launch)
    city: varchar("city", { length: 255 }),
    province: varchar("province", { length: 255 }),
    country: varchar("country", { length: 255 }).default("Zambia").notNull(),
    // Profile content
    bio: text("bio"),
    avatarUrl: text("avatar_url"),
    headline: varchar("headline", { length: 500 }),
    // Professional status
    availabilityStatus: mysqlEnum("availability_status", [
      "available",
      "open_to_opportunities",
      "not_available",
      "in_quickwork",
    ])
      .default("available")
      .notNull(),
    lookingForWork: boolean("looking_for_work").default(true).notNull(),
    // Onboarding progress
    onboardingCompleted: boolean("onboarding_completed").default(false).notNull(),
    levav28Day: int("levav_28_day").default(0).notNull(), // 0-28 progress
    levav28Completed: boolean("levav_28_completed").default(false).notNull(),
    // Aggregate WRI score snapshot (denormalized for fast reads)
    currentWriScore: decimal("current_wri_score", { precision: 5, scale: 2 }),
    wriGoldKey: mysqlEnum("wri_gold_key", ["bronze", "silver", "gold", "platinum", "diamond"]),
    // Timestamps
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .defaultNow()
      .notNull()
      .$onUpdate(() => new Date()),
  },
  (table) => ({
    userIdIdx: uniqueIndex("profiles_user_id_idx").on(table.userId),
    levavCodeIdx: uniqueIndex("profiles_levav_code_idx").on(table.levavCode),
    professionIdIdx: index("profiles_profession_id_idx").on(table.professionId),
    availabilityIdx: index("profiles_availability_idx").on(table.availabilityStatus),
    lookingForWorkIdx: index("profiles_looking_for_work_idx").on(table.lookingForWork),
    wriScoreIdx: index("profiles_wri_score_idx").on(table.currentWriScore),
    countryIdx: index("profiles_country_idx").on(table.country),
  })
);

export type LevavProfile = typeof levavProfiles.$inferSelect;
export type InsertLevavProfile = typeof levavProfiles.$inferInsert;

/* ============================================================
   SECTION 2: WRI ANALYTICS
   ============================================================ */

/**
 * wri_analytics — Workforce Readiness Index master record.
 * Stores the current computed WRI score and all 7 component scores.
 * Updated by backend triggers after significant profile events.
 */
export const wriAnalytics = mysqlTable(
  "wri_analytics",
  {
    id: serial("id").primaryKey(),
    profileId: bigint("profile_id", { mode: "number", unsigned: true })
      .notNull()
      .unique(), // 1:1 with levav_profiles

    // The global WRI score (0.00 - 100.00)
    wriScore: decimal("wri_score", { precision: 5, scale: 2 }).notNull().default("0.00"),
    // Gold Key badge tier derived from wri_score
    goldKeyTier: mysqlEnum("gold_key_tier", [
      "bronze",   // 0-39
      "silver",   // 40-59
      "gold",     // 60-74
      "platinum", // 75-89
      "diamond",  // 90-100
    ])
      .default("bronze")
      .notNull(),

    // The 7 component scores (each 0.00 - 100.00)
    cultureScore: decimal("culture_score", { precision: 5, scale: 2 }).notNull().default("0.00"),
    criticalThinkingScore: decimal("critical_thinking_score", { precision: 5, scale: 2 })
      .notNull()
      .default("0.00"),
    reliabilityScore: decimal("reliability_score", { precision: 5, scale: 2 })
      .notNull()
      .default("0.00"),
    communicationScore: decimal("communication_score", { precision: 5, scale: 2 })
      .notNull()
      .default("0.00"),
    learningScore: decimal("learning_score", { precision: 5, scale: 2 }).notNull().default("0.00"),
    leadershipScore: decimal("leadership_score", { precision: 5, scale: 2 })
      .notNull()
      .default("0.00"),
    impactScore: decimal("impact_score", { precision: 5, scale: 2 }).notNull().default("0.00"),

    // Calculation metadata
    calculationVersion: int("calculation_version").default(1).notNull(),
    lastCalculatedAt: timestamp("last_calculated_at").defaultNow().notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .defaultNow()
      .notNull()
      .$onUpdate(() => new Date()),
  },
  (table) => ({
    profileIdIdx: uniqueIndex("wri_profile_id_idx").on(table.profileId),
    wriScoreIdx: index("wri_score_idx").on(table.wriScore),
    goldKeyIdx: index("wri_gold_key_idx").on(table.goldKeyTier),
  })
);

export type WriAnalytics = typeof wriAnalytics.$inferSelect;
export type InsertWriAnalytics = typeof wriAnalytics.$inferInsert;

/**
 * wri_component_scores — Historical record of individual component score changes.
 * Every WRI recalculation inserts a row here for audit trail and trend analysis.
 */
export const wriComponentScores = mysqlTable(
  "wri_component_scores",
  {
    id: serial("id").primaryKey(),
    profileId: bigint("profile_id", { mode: "number", unsigned: true }).notNull(),
    // Which WRI component was updated
    componentType: mysqlEnum("component_type", [
      "culture",
      "critical_thinking",
      "reliability",
      "communication",
      "learning",
      "leadership",
      "impact",
    ]).notNull(),
    // The new score value
    score: decimal("score", { precision: 5, scale: 2 }).notNull(),
    // Weight applied in the global WRI calculation (0.00 - 1.00)
    weight: decimal("weight", { precision: 3, scale: 2 }).notNull().default("0.14"),
    // Source of the score change (for traceability)
    sourceEvent: mysqlEnum("source_event", [
      "levav_28_session",
      "volunteer_validation",
      "course_completion",
      "quickwork_shift",
      "employer_review",
      "skill_verification",
      "admin_override",
      "manual_update",
    ]).notNull(),
    // Reference to the source entity (e.g. session_id, shift_id, course_id)
    sourceEntityId: bigint("source_entity_id", { mode: "number", unsigned: true }),
    // Narrative context for the score change
    sourceDescription: varchar("source_description", { length: 500 }),
    recordedAt: timestamp("recorded_at").defaultNow().notNull(),
  },
  (table) => ({
    profileIdIdx: index("wri_comp_profile_id_idx").on(table.profileId),
    componentTypeIdx: index("wri_comp_component_type_idx").on(table.componentType),
    sourceEventIdx: index("wri_comp_source_event_idx").on(table.sourceEvent),
    recordedAtIdx: index("wri_comp_recorded_at_idx").on(table.recordedAt),
  })
);

export type WriComponentScore = typeof wriComponentScores.$inferSelect;
export type InsertWriComponentScore = typeof wriComponentScores.$inferInsert;

/* ============================================================
   SECTION 3: LEVAV 28 ONBOARDING
   ============================================================ */

/**
 * levav_code_acceptances — Record of The Levav Code covenant acceptance.
 * Unskippable modal during initial registration.
 */
export const levavCodeAcceptances = mysqlTable(
  "levav_code_acceptances",
  {
    id: serial("id").primaryKey(),
    profileId: bigint("profile_id", { mode: "number", unsigned: true }).notNull(),
    // The 8 pillars of The Levav Code (all must be true)
    ownershipAccepted: boolean("ownership_accepted").default(true).notNull(),
    excellenceAccepted: boolean("excellence_accepted").default(true).notNull(),
    reliabilityAccepted: boolean("reliability_accepted").default(true).notNull(),
    initiativeAccepted: boolean("initiative_accepted").default(true).notNull(),
    growthAccepted: boolean("growth_accepted").default(true).notNull(),
    criticalThinkingAccepted: boolean("critical_thinking_accepted").default(true).notNull(),
    serviceAccepted: boolean("service_accepted").default(true).notNull(),
    impactAccepted: boolean("impact_accepted").default(true).notNull(),
    // Audit
    ipAddress: varchar("ip_address", { length: 100 }),
    userAgent: text("user_agent"),
    acceptedAt: timestamp("accepted_at").defaultNow().notNull(),
  },
  (table) => ({
    profileIdIdx: uniqueIndex("levav_code_profile_id_idx").on(table.profileId),
  })
);

export type LevavCodeAcceptance = typeof levavCodeAcceptances.$inferSelect;
export type InsertLevavCodeAcceptance = typeof levavCodeAcceptances.$inferInsert;

/**
 * levav_28_sessions — Daily socratic onboarding session record.
 * 28-day progressive friction engine. Each row = one day's session.
 */
export const levav28Sessions = mysqlTable(
  "levav_28_sessions",
  {
    id: serial("id").primaryKey(),
    profileId: bigint("profile_id", { mode: "number", unsigned: true }).notNull(),
    dayNumber: int("day_number").notNull(), // 1 - 28

    // CONFRONT: AI-generated scenario for the user's profession
    confrontScenario: text("confront_scenario"),

    // DISSECT: User's root-cause analysis (paste-disabled, typed only)
    dissectResponse: text("dissect_response"),

    // OWN: User's personal responsibility analysis
    ownAnalysis: text("own_analysis"),

    // EXECUTE: Tactical solution plan (typed or Whisper voice dictation)
    executePlan: text("execute_plan"),

    // AI evaluation feedback
    aiFeedback: text("ai_feedback"),
    aiScore: decimal("ai_score", { precision: 5, scale: 2 }), // 0-100 rating

    // Session state
    status: mysqlEnum("status", ["started", "in_progress", "submitted", "evaluated", "completed"])
      .default("started")
      .notNull(),

    // Timestamps
    startedAt: timestamp("started_at").defaultNow().notNull(),
    submittedAt: timestamp("submitted_at"),
    completedAt: timestamp("completed_at"),
  },
  (table) => ({
    profileDayIdx: uniqueIndex("levav28_profile_day_idx").on(table.profileId, table.dayNumber),
    profileIdIdx: index("levav28_profile_id_idx").on(table.profileId),
    statusIdx: index("levav28_status_idx").on(table.status),
  })
);

export type Levav28Session = typeof levav28Sessions.$inferSelect;
export type InsertLevav28Session = typeof levav28Sessions.$inferInsert;

/**
 * levav_28_responses — Individual challenge responses within a session.
 * Breaks down each session into the 4 challenge phases for granular tracking.
 */
export const levav28Responses = mysqlTable(
  "levav_28_responses",
  {
    id: serial("id").primaryKey(),
    sessionId: bigint("session_id", { mode: "number", unsigned: true }).notNull(),
    challengeType: mysqlEnum("challenge_type", ["confront", "dissect", "own", "execute"])
      .notNull(),
    responseText: text("response_text").notNull(),
    // AI evaluation
    aiEvaluation: text("ai_evaluation"),
    aiPassed: boolean("ai_passed"), // null = not yet evaluated
    // Score contribution to WRI components
    scoreContribution: decimal("score_contribution", { precision: 5, scale: 2 }),
    wriComponentAffected: mysqlEnum("wri_component_affected", [
      "culture",
      "critical_thinking",
      "reliability",
      "communication",
      "learning",
      "leadership",
      "impact",
    ]),
    submittedAt: timestamp("submitted_at").defaultNow().notNull(),
    evaluatedAt: timestamp("evaluated_at"),
  },
  (table) => ({
    sessionIdIdx: index("levav28_resp_session_id_idx").on(table.sessionId),
    challengeTypeIdx: index("levav28_resp_challenge_type_idx").on(table.challengeType),
  })
);

export type Levav28Response = typeof levav28Responses.$inferSelect;
export type InsertLevav28Response = typeof levav28Responses.$inferInsert;

/* ============================================================
   SECTION 4: PROFESSIONAL DATA
   ============================================================ */

/**
 * skills_inventory — User-declared and verified skills.
 * Each skill links to a profile and tracks proficiency.
 */
export const skillsInventory = mysqlTable(
  "skills_inventory",
  {
    id: serial("id").primaryKey(),
    profileId: bigint("profile_id", { mode: "number", unsigned: true }).notNull(),
    skillName: varchar("skill_name", { length: 255 }).notNull(),
    proficiencyLevel: mysqlEnum("proficiency_level", [
      "beginner",
      "intermediate",
      "advanced",
      "expert",
      "master",
    ])
      .default("beginner")
      .notNull(),
    // Verification: self-declared, peer-endorsed, or assessed
    verifiedBy: mysqlEnum("verified_by", ["self", "peer", "assessment", "employer"])
      .default("self")
      .notNull(),
    verifiedAt: timestamp("verified_at"),
    // Skill category for grouping
    category: varchar("category", { length: 255 }),
    // Endorsement count (peer endorsements)
    endorsementCount: int("endorsement_count").default(0).notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => ({
    profileIdIdx: index("skills_profile_id_idx").on(table.profileId),
    skillNameIdx: index("skills_skill_name_idx").on(table.skillName),
    proficiencyIdx: index("skills_proficiency_idx").on(table.proficiencyLevel),
  })
);

export type SkillsInventory = typeof skillsInventory.$inferSelect;
export type InsertSkillsInventory = typeof skillsInventory.$inferInsert;

/**
 * experience_history — Work, volunteer, and project experience records.
 * Feeds into the Levav ID portfolio display.
 */
export const experienceHistory = mysqlTable(
  "experience_history",
  {
    id: serial("id").primaryKey(),
    profileId: bigint("profile_id", { mode: "number", unsigned: true }).notNull(),
    title: varchar("title", { length: 255 }).notNull(),
    organization: varchar("organization", { length: 255 }).notNull(),
    experienceType: mysqlEnum("experience_type", ["work", "volunteer", "project", "internship", "contract"])
      .notNull(),
    description: text("description"),
    location: varchar("location", { length: 255 }),
    startDate: date("start_date").notNull(),
    endDate: date("end_date"),
    isCurrent: boolean("is_current").default(false).notNull(),
    // Skills used/gained in this role
    skillsUsed: json("skills_used").$type<string[]>(),
    // Verification
    verified: boolean("verified").default(false).notNull(),
    verifiedBy: varchar("verified_by", { length: 255 }),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => ({
    profileIdIdx: index("exp_profile_id_idx").on(table.profileId),
    experienceTypeIdx: index("exp_type_idx").on(table.experienceType),
  })
);

export type ExperienceHistory = typeof experienceHistory.$inferSelect;
export type InsertExperienceHistory = typeof experienceHistory.$inferInsert;

/**
 * education_history — Formal education and training records.
 */
export const educationHistory = mysqlTable(
  "education_history",
  {
    id: serial("id").primaryKey(),
    profileId: bigint("profile_id", { mode: "number", unsigned: true }).notNull(),
    institution: varchar("institution", { length: 255 }).notNull(),
    degree: varchar("degree", { length: 255 }).notNull(), // e.g. "Bachelor of Science"
    fieldOfStudy: varchar("field_of_study", { length: 255 }),
    grade: varchar("grade", { length: 50 }), // GPA or classification
    startDate: date("start_date"),
    endDate: date("end_date"),
    isCurrent: boolean("is_current").default(false).notNull(),
    description: text("description"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => ({
    profileIdIdx: index("edu_profile_id_idx").on(table.profileId),
  })
);

export type EducationHistory = typeof educationHistory.$inferSelect;
export type InsertEducationHistory = typeof educationHistory.$inferInsert;

/* ============================================================
   SECTION 5: CREATOR STUDIO (Levav Learn)
   ============================================================ */

/**
 * creator_studio_courses — Courses and learning content.
 * Created by verified creators (role === 'creator').
 */
export const creatorStudioCourses = mysqlTable(
  "creator_studio_courses",
  {
    id: serial("id").primaryKey(),
    creatorId: bigint("creator_id", { mode: "number", unsigned: true }).notNull(), // FK → users (role=creator)
    title: varchar("title", { length: 500 }).notNull(),
    description: text("description"),
    category: varchar("category", { length: 255 }),
    // Tier determines access rules
    tier: mysqlEnum("tier", ["free", "subscription", "paid"]).default("free").notNull(),
    // Pricing (for paid tier)
    price: decimal("price", { precision: 10, scale: 2 }),
    currency: varchar("currency", { length: 10 }).default("ZMW").notNull(),
    // Media
    thumbnailUrl: text("thumbnail_url"),
    durationMinutes: int("duration_minutes"),
    // Publishing state
    isPublished: boolean("is_published").default(false).notNull(),
    publishedAt: timestamp("published_at"),
    // Admin audit
    reviewedByAdmin: boolean("reviewed_by_admin").default(false).notNull(),
    adminNotes: text("admin_notes"),
    // Metadata
    totalEnrollments: int("total_enrollments").default(0).notNull(),
    averageRating: decimal("average_rating", { precision: 3, scale: 2 }),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .defaultNow()
      .notNull()
      .$onUpdate(() => new Date()),
  },
  (table) => ({
    creatorIdIdx: index("courses_creator_id_idx").on(table.creatorId),
    tierIdx: index("courses_tier_idx").on(table.tier),
    categoryIdx: index("courses_category_idx").on(table.category),
    publishedIdx: index("courses_published_idx").on(table.isPublished),
  })
);

export type CreatorStudioCourse = typeof creatorStudioCourses.$inferSelect;
export type InsertCreatorStudioCourse = typeof creatorStudioCourses.$inferInsert;

/**
 * course_lessons — Individual lessons within a course.
 * All media plays inside the secure internal Levav media frame.
 */
export const courseLessons = mysqlTable(
  "course_lessons",
  {
    id: serial("id").primaryKey(),
    courseId: bigint("course_id", { mode: "number", unsigned: true }).notNull(),
    title: varchar("title", { length: 500 }).notNull(),
    description: text("description"),
    contentType: mysqlEnum("content_type", ["video", "audio", "pdf", "presentation", "text", "quiz"])
      .notNull(),
    contentUrl: text("content_url"), // Internal secure URL
    durationMinutes: int("duration_minutes"),
    sortOrder: int("sort_order").notNull(),
    isFreePreview: boolean("is_free_preview").default(false).notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => ({
    courseIdIdx: index("lessons_course_id_idx").on(table.courseId),
    sortOrderIdx: index("lessons_sort_order_idx").on(table.courseId, table.sortOrder),
  })
);

export type CourseLesson = typeof courseLessons.$inferSelect;
export type InsertCourseLesson = typeof courseLessons.$inferInsert;

/**
 * course_enrollments — User enrollment records.
 */
export const courseEnrollments = mysqlTable(
  "course_enrollments",
  {
    id: serial("id").primaryKey(),
    profileId: bigint("profile_id", { mode: "number", unsigned: true }).notNull(),
    courseId: bigint("course_id", { mode: "number", unsigned: true }).notNull(),
    status: mysqlEnum("status", ["active", "completed", "dropped", "expired"])
      .default("active")
      .notNull(),
    enrolledAt: timestamp("enrolled_at").defaultNow().notNull(),
    completedAt: timestamp("completed_at"),
  },
  (table) => ({
    profileCourseIdx: uniqueIndex("enrollments_profile_course_idx").on(table.profileId, table.courseId),
    profileIdIdx: index("enrollments_profile_id_idx").on(table.profileId),
    courseIdIdx: index("enrollments_course_id_idx").on(table.courseId),
  })
);

export type CourseEnrollment = typeof courseEnrollments.$inferSelect;
export type InsertCourseEnrollment = typeof courseEnrollments.$inferInsert;

/**
 * course_progress — Lesson completion tracking.
 */
export const courseProgress = mysqlTable(
  "course_progress",
  {
    id: serial("id").primaryKey(),
    enrollmentId: bigint("enrollment_id", { mode: "number", unsigned: true }).notNull(),
    lessonId: bigint("lesson_id", { mode: "number", unsigned: true }).notNull(),
    completed: boolean("completed").default(false).notNull(),
    completedAt: timestamp("completed_at"),
    progressPercent: int("progress_percent").default(0).notNull(),
    timeSpentSeconds: int("time_spent_seconds").default(0).notNull(),
  },
  (table) => ({
    enrollmentLessonIdx: uniqueIndex("progress_enrollment_lesson_idx").on(
      table.enrollmentId,
      table.lessonId
    ),
  })
);

export type CourseProgress = typeof courseProgress.$inferSelect;
export type InsertCourseProgress = typeof courseProgress.$inferInsert;

/* ============================================================
   SECTION 6: QUICKWORK
   ============================================================ */

/**
 * quickwork_shifts — On-demand shift listings.
 * Employers publish shifts; talent applies and gets matched.
 */
export const quickworkShifts = mysqlTable(
  "quickwork_shifts",
  {
    id: serial("id").primaryKey(),
    employerId: bigint("employer_id", { mode: "number", unsigned: true }).notNull(), // FK → employer_profiles
    title: varchar("title", { length: 500 }).notNull(),
    description: text("description"),
    location: varchar("location", { length: 500 }),
    city: varchar("city", { length: 255 }),
    province: varchar("province", { length: 255 }),
    shiftDate: date("shift_date").notNull(),
    startTime: varchar("start_time", { length: 10 }).notNull(), // HH:MM format
    endTime: varchar("end_time", { length: 10 }).notNull(),
    // Compensation
    hourlyRate: decimal("hourly_rate", { precision: 10, scale: 2 }).notNull(),
    currency: varchar("currency", { length: 10 }).default("ZMW").notNull(),
    totalHours: decimal("total_hours", { precision: 4, scale: 1 }).notNull(),
    estimatedTotalPay: decimal("estimated_total_pay", { precision: 10, scale: 2 }),
    // Requirements
    requiredSkills: json("required_skills").$type<string[]>(),
    requiredProfessions: json("required_professions").$type<string[]>(),
    minWriScore: decimal("min_wri_score", { precision: 5, scale: 2 }),
    // State
    status: mysqlEnum("status", ["open", "filled", "in_progress", "completed", "cancelled"])
      .default("open")
      .notNull(),
    spotsTotal: int("spots_total").default(1).notNull(),
    spotsFilled: int("spots_filled").default(0).notNull(),
    filledByProfileId: bigint("filled_by_profile_id", { mode: "number", unsigned: true }),
    // Timestamps
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .defaultNow()
      .notNull()
      .$onUpdate(() => new Date()),
  },
  (table) => ({
    employerIdIdx: index("shifts_employer_id_idx").on(table.employerId),
    statusIdx: index("shifts_status_idx").on(table.status),
    shiftDateIdx: index("shifts_date_idx").on(table.shiftDate),
    cityIdx: index("shifts_city_idx").on(table.city),
  })
);

export type QuickworkShift = typeof quickworkShifts.$inferSelect;
export type InsertQuickworkShift = typeof quickworkShifts.$inferInsert;

/**
 * quickwork_applications — Shift applications from talent.
 */
export const quickworkApplications = mysqlTable(
  "quickwork_applications",
  {
    id: serial("id").primaryKey(),
    shiftId: bigint("shift_id", { mode: "number", unsigned: true }).notNull(),
    profileId: bigint("profile_id", { mode: "number", unsigned: true }).notNull(),
    status: mysqlEnum("status", ["applied", "shortlisted", "accepted", "rejected", "withdrawn", "no_show"])
      .default("applied")
      .notNull(),
    coverNote: text("cover_note"),
    appliedAt: timestamp("applied_at").defaultNow().notNull(),
    acceptedAt: timestamp("accepted_at"),
    // Post-shift employer rating
    employerRating: int("employer_rating"), // 1-5
    employerReview: text("employer_review"),
    // Post-shift talent rating
    talentRating: int("talent_rating"), // 1-5
    talentReview: text("talent_review"),
    completedAt: timestamp("completed_at"),
  },
  (table) => ({
    shiftProfileIdx: uniqueIndex("quickapp_shift_profile_idx").on(table.shiftId, table.profileId),
    shiftIdIdx: index("quickapp_shift_id_idx").on(table.shiftId),
    profileIdIdx: index("quickapp_profile_id_idx").on(table.profileId),
  })
);

export type QuickworkApplication = typeof quickworkApplications.$inferSelect;
export type InsertQuickworkApplication = typeof quickworkApplications.$inferInsert;

/* ============================================================
   SECTION 7: IMPACT (Levav Impact)
   ============================================================ */

/**
 * impact_partners — Vetted impact organizations.
 * Organizations must be verified by admin before listing opportunities.
 */
export const impactPartners = mysqlTable(
  "impact_partners",
  {
    id: serial("id").primaryKey(),
    name: varchar("name", { length: 255 }).notNull(),
    description: text("description"),
    logoUrl: text("logo_url"),
    website: varchar("website", { length: 500 }),
    contactEmail: varchar("contact_email", { length: 320 }),
    contactPhone: varchar("contact_phone", { length: 50 }),
    // Classification
    sector: varchar("sector", { length: 255 }), // e.g. "education", "health", "environment"
    registrationNumber: varchar("registration_number", { length: 255 }),
    // Location
    city: varchar("city", { length: 255 }),
    province: varchar("province", { length: 255 }),
    country: varchar("country", { length: 255 }).default("Zambia").notNull(),
    // Verification
    verificationStatus: mysqlEnum("verification_status", ["pending", "verified", "rejected", "suspended"])
      .default("pending")
      .notNull(),
    verifiedByAdminId: bigint("verified_by_admin_id", { mode: "number", unsigned: true }), // FK → users (admin)
    verifiedAt: timestamp("verified_at"),
    adminNotes: text("admin_notes"),
    // Metrics
    totalOpportunitiesListed: int("total_opportunities_listed").default(0).notNull(),
    totalVolunteerHoursLogged: decimal("total_volunteer_hours_logged", { precision: 10, scale: 1 })
      .default("0.0")
      .notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .defaultNow()
      .notNull()
      .$onUpdate(() => new Date()),
  },
  (table) => ({
    verificationStatusIdx: index("partners_verification_idx").on(table.verificationStatus),
    sectorIdx: index("partners_sector_idx").on(table.sector),
    countryIdx: index("partners_country_idx").on(table.country),
  })
);

export type ImpactPartner = typeof impactPartners.$inferSelect;
export type InsertImpactPartner = typeof impactPartners.$inferInsert;

/**
 * impact_opportunities — Available volunteer/community impact roles.
 */
export const impactOpportunities = mysqlTable(
  "impact_opportunities",
  {
    id: serial("id").primaryKey(),
    partnerId: bigint("partner_id", { mode: "number", unsigned: true }).notNull(),
    title: varchar("title", { length: 500 }).notNull(),
    description: text("description"),
    location: varchar("location", { length: 500 }),
    city: varchar("city", { length: 255 }),
    province: varchar("province", { length: 255 }),
    requiredSkills: json("required_skills").$type<string[]>(),
    timeCommitmentHours: decimal("time_commitment_hours", { precision: 5, scale: 1 }),
    startDate: date("start_date"),
    endDate: date("end_date"),
    spotsAvailable: int("spots_available").default(1).notNull(),
    spotsFilled: int("spots_filled").default(0).notNull(),
    status: mysqlEnum("status", ["open", "filled", "in_progress", "completed", "cancelled"])
      .default("open")
      .notNull(),
    coordinatorName: varchar("coordinator_name", { length: 255 }),
    coordinatorEmail: varchar("coordinator_email", { length: 320 }),
    coordinatorPhone: varchar("coordinator_phone", { length: 50 }),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => ({
    partnerIdIdx: index("opportunities_partner_id_idx").on(table.partnerId),
    statusIdx: index("opportunities_status_idx").on(table.status),
    cityIdx: index("opportunities_city_idx").on(table.city),
  })
);

export type ImpactOpportunity = typeof impactOpportunities.$inferSelect;
export type InsertImpactOpportunity = typeof impactOpportunities.$inferInsert;

/**
 * volunteer_ledger — Record of volunteer hours logged.
 * Validated by site coordinator; triggers WRI Impact Score recalculation.
 */
export const volunteerLedger = mysqlTable(
  "volunteer_ledger",
  {
    id: serial("id").primaryKey(),
    opportunityId: bigint("opportunity_id", { mode: "number", unsigned: true }).notNull(),
    profileId: bigint("profile_id", { mode: "number", unsigned: true }).notNull(),
    hoursLogged: decimal("hours_logged", { precision: 5, scale: 1 }).notNull(),
    activityDescription: text("activity_description"),
    logDate: date("log_date").notNull(),
    // Validation by site coordinator
    validatedByCoordinator: boolean("validated_by_coordinator").default(false).notNull(),
    coordinatorName: varchar("coordinator_name", { length: 255 }),
    coordinatorId: bigint("coordinator_id", { mode: "number", unsigned: true }), // If coordinator has a system account
    validatedAt: timestamp("validated_at"),
    // WRI impact
    impactScoreContribution: decimal("impact_score_contribution", { precision: 5, scale: 2 }),
    // Admin
    notes: text("notes"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => ({
    profileIdIdx: index("volunteer_profile_id_idx").on(table.profileId),
    opportunityIdIdx: index("volunteer_opportunity_id_idx").on(table.opportunityId),
    validatedIdx: index("volunteer_validated_idx").on(table.validatedByCoordinator),
    logDateIdx: index("volunteer_log_date_idx").on(table.logDate),
  })
);

export type VolunteerLedger = typeof volunteerLedger.$inferSelect;
export type InsertVolunteerLedger = typeof volunteerLedger.$inferInsert;

/* ============================================================
   SECTION 8: EMPLOYER B2B
   ============================================================ */

/**
 * employer_profiles — B2B employer accounts (1:1 with users where role='employer').
 */
export const employerProfiles = mysqlTable(
  "employer_profiles",
  {
    id: serial("id").primaryKey(),
    userId: bigint("user_id", { mode: "number", unsigned: true }).notNull().unique(),
    // Company details
    companyName: varchar("company_name", { length: 255 }).notNull(),
    registrationNumber: varchar("registration_number", { length: 255 }),
    industry: varchar("industry", { length: 255 }),
    companySize: mysqlEnum("company_size", ["startup", "small", "medium", "large", "enterprise"]),
    website: varchar("website", { length: 500 }),
    description: text("description"),
    logoUrl: text("logo_url"),
    // Contact
    contactName: varchar("contact_name", { length: 255 }),
    contactPhone: varchar("contact_phone", { length: 50 }),
    contactEmail: varchar("contact_email", { length: 320 }),
    // Location
    city: varchar("city", { length: 255 }),
    province: varchar("province", { length: 255 }),
    country: varchar("country", { length: 255 }).default("Zambia").notNull(),
    // Verification & subscription
    verificationStatus: mysqlEnum("verification_status", [
      "pending",
      "verified",
      "rejected",
      "suspended",
    ])
      .default("pending")
      .notNull(),
    subscriptionTier: mysqlEnum("subscription_tier", ["basic", "professional", "enterprise"])
      .default("basic")
      .notNull(),
    subscriptionExpiresAt: timestamp("subscription_expires_at"),
    // Metrics
    totalJobPostings: int("total_job_postings").default(0).notNull(),
    totalQuickworkShifts: int("total_quickwork_shifts").default(0).notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .defaultNow()
      .notNull()
      .$onUpdate(() => new Date()),
  },
  (table) => ({
    userIdIdx: uniqueIndex("employers_user_id_idx").on(table.userId),
    verificationIdx: index("employers_verification_idx").on(table.verificationStatus),
    industryIdx: index("employers_industry_idx").on(table.industry),
    countryIdx: index("employers_country_idx").on(table.country),
  })
);

export type EmployerProfile = typeof employerProfiles.$inferSelect;
export type InsertEmployerProfile = typeof employerProfiles.$inferInsert;

/**
 * job_postings — Corporate job openings posted by employers.
 */
export const jobPostings = mysqlTable(
  "job_postings",
  {
    id: serial("id").primaryKey(),
    employerId: bigint("employer_id", { mode: "number", unsigned: true }).notNull(),
    title: varchar("title", { length: 500 }).notNull(),
    description: text("description"),
    requirements: text("requirements"),
    responsibilities: text("responsibilities"),
    location: varchar("location", { length: 500 }),
    city: varchar("city", { length: 255 }),
    province: varchar("province", { length: 255 }),
    country: varchar("country", { length: 255 }).default("Zambia").notNull(),
    // Job classification
    jobType: mysqlEnum("job_type", ["full_time", "part_time", "contract", "internship", "remote"])
      .notNull(),
    experienceLevel: mysqlEnum("experience_level", ["entry", "mid", "senior", "lead", "executive"]),
    // Compensation
    salaryMin: decimal("salary_min", { precision: 12, scale: 2 }),
    salaryMax: decimal("salary_max", { precision: 12, scale: 2 }),
    currency: varchar("currency", { length: 10 }).default("ZMW").notNull(),
    // Requirements
    skillsRequired: json("skills_required").$type<string[]>(),
    minWriScore: decimal("min_wri_score", { precision: 5, scale: 2 }),
    // State
    status: mysqlEnum("status", ["draft", "published", "paused", "closed", "filled"])
      .default("draft")
      .notNull(),
    postedAt: timestamp("posted_at"),
    closesAt: timestamp("closes_at"),
    totalApplications: int("total_applications").default(0).notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .defaultNow()
      .notNull()
      .$onUpdate(() => new Date()),
  },
  (table) => ({
    employerIdIdx: index("jobs_employer_id_idx").on(table.employerId),
    statusIdx: index("jobs_status_idx").on(table.status),
    jobTypeIdx: index("jobs_type_idx").on(table.jobType),
    cityIdx: index("jobs_city_idx").on(table.city),
    wriScoreIdx: index("jobs_wri_score_idx").on(table.minWriScore),
    postedAtIdx: index("jobs_posted_at_idx").on(table.postedAt),
  })
);

export type JobPosting = typeof jobPostings.$inferSelect;
export type InsertJobPosting = typeof jobPostings.$inferInsert;

/**
 * job_applications — Talent applications for job postings.
 */
export const jobApplications = mysqlTable(
  "job_applications",
  {
    id: serial("id").primaryKey(),
    jobId: bigint("job_id", { mode: "number", unsigned: true }).notNull(),
    profileId: bigint("profile_id", { mode: "number", unsigned: true }).notNull(),
    coverLetter: text("cover_letter"),
    status: mysqlEnum("status", [
      "applied",
      "screening",
      "interview",
      "offer",
      "hired",
      "rejected",
      "withdrawn",
    ])
      .default("applied")
      .notNull(),
    appliedAt: timestamp("applied_at").defaultNow().notNull(),
    // Pipeline timestamps
    screenedAt: timestamp("screened_at"),
    interviewedAt: timestamp("interviewed_at"),
    offeredAt: timestamp("offered_at"),
    hiredAt: timestamp("hired_at"),
    rejectedAt: timestamp("rejected_at"),
    // Employer notes
    employerNotes: text("employer_notes"),
    rating: int("rating"), // 1-5 internal rating
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .defaultNow()
      .notNull()
      .$onUpdate(() => new Date()),
  },
  (table) => ({
    jobProfileIdx: uniqueIndex("jobapps_job_profile_idx").on(table.jobId, table.profileId),
    jobIdIdx: index("jobapps_job_id_idx").on(table.jobId),
    profileIdIdx: index("jobapps_profile_id_idx").on(table.profileId),
    statusIdx: index("jobapps_status_idx").on(table.status),
  })
);

export type JobApplication = typeof jobApplications.$inferSelect;
export type InsertJobApplication = typeof jobApplications.$inferInsert;

/* ============================================================
   SECTION 9: FINANCIAL (Levav Wallet)
   ============================================================ */

/**
 * transactions_wallet — The internal temporary settlement data store.
 * Routes QuickWork earnings, course sales, subscriptions, donations, refunds.
 */
export const transactionsWallet = mysqlTable(
  "transactions_wallet",
  {
    id: serial("id").primaryKey(),
    // The party this transaction affects (polymorphic via type fields)
    profileId: bigint("profile_id", { mode: "number", unsigned: true }), // talent/creator
    employerId: bigint("employer_id", { mode: "number", unsigned: true }), // employer
    partnerId: bigint("partner_id", { mode: "number", unsigned: true }), // impact partner

    // Transaction classification
    transactionType: mysqlEnum("transaction_type", [
      "quickwork_earning",
      "quickwork_payout",
      "course_sale",
      "course_payout",
      "subscription_revenue",
      "subscription_fee",
      "donation",
      "honorarium",
      "employer_subscription_fee",
      "refund",
      "platform_commission",
      "withdrawal",
      "deposit",
    ]).notNull(),

    // Financials
    amount: decimal("amount", { precision: 12, scale: 2 }).notNull(),
    currency: varchar("currency", { length: 10 }).default("ZMW").notNull(),
    platformCommission: decimal("platform_commission", { precision: 12, scale: 2 }).default("0.00"),
    netAmount: decimal("net_amount", { precision: 12, scale: 2 }),
    description: varchar("description", { length: 500 }),

    // Payment method (Zambia-focused)
    paymentMethod: mysqlEnum("payment_method", [
      "momo_airtel",
      "momo_mtn",
      "momo_zamtel",
      "flutterwave",
      "dpo_pay",
      "techpay",
      "visa",
      "mastercard",
      "bank_transfer",
      "internal",
    ]),

    // Status
    status: mysqlEnum("status", ["pending", "processing", "completed", "failed", "cancelled", "refunded"])
      .default("pending")
      .notNull(),

    // External payment reference
    externalReference: varchar("external_reference", { length: 500 }),
    externalProvider: varchar("external_provider", { length: 255 }),
    settledAt: timestamp("settled_at"),

    // Related entity reference (polymorphic)
    relatedEntityType: mysqlEnum("related_entity_type", [
      "quickwork_shift",
      "course",
      "subscription",
      "job_posting",
      "volunteer_opportunity",
    ]),
    relatedEntityId: bigint("related_entity_id", { mode: "number", unsigned: true }),

    // Revenue sharing (if applicable)
    revenueSharePercent: decimal("revenue_share_percent", { precision: 5, scale: 2 }),
    revenueShareRecipientId: bigint("revenue_share_recipient_id", {
      mode: "number",
      unsigned: true,
    }),

    // Audit trail
    ipAddress: varchar("ip_address", { length: 100 }),
    metadata: json("metadata").$type<Record<string, unknown>>(),

    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .defaultNow()
      .notNull()
      .$onUpdate(() => new Date()),
  },
  (table) => ({
    profileIdIdx: index("wallet_profile_id_idx").on(table.profileId),
    employerIdIdx: index("wallet_employer_id_idx").on(table.employerId),
    typeIdx: index("wallet_transaction_type_idx").on(table.transactionType),
    statusIdx: index("wallet_status_idx").on(table.status),
    externalRefIdx: index("wallet_external_ref_idx").on(table.externalReference),
    createdAtIdx: index("wallet_created_at_idx").on(table.createdAt),
  })
);

export type TransactionsWallet = typeof transactionsWallet.$inferSelect;
export type InsertTransactionsWallet = typeof transactionsWallet.$inferInsert;

/* ============================================================
   SECTION 10: SYSTEM
   ============================================================ */

/**
 * notifications — System notification records.
 * Delivered via in-app notification center.
 */
export const notifications = mysqlTable(
  "notifications",
  {
    id: serial("id").primaryKey(),
    recipientId: bigint("recipient_id", { mode: "number", unsigned: true }).notNull(), // FK → users
    // Notification classification
    type: mysqlEnum("type", [
      "wri_update",
      "levav_28_reminder",
      "shift_match",
      "shift_approved",
      "job_application_update",
      "course_update",
      "volunteer_validation",
      "wallet_transaction",
      "system_announcement",
      "employer_message",
      "impact_opportunity",
    ]).notNull(),
    title: varchar("title", { length: 255 }).notNull(),
    message: text("message").notNull(),
    // Deep link reference
    relatedEntityType: varchar("related_entity_type", { length: 50 }),
    relatedEntityId: bigint("related_entity_id", { mode: "number", unsigned: true }),
    actionUrl: varchar("action_url", { length: 500 }),
    // State
    isRead: boolean("is_read").default(false).notNull(),
    readAt: timestamp("read_at"),
    // Priority
    priority: mysqlEnum("priority", ["low", "normal", "high", "urgent"])
      .default("normal")
      .notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => ({
    recipientIdIdx: index("notif_recipient_id_idx").on(table.recipientId),
    typeIdx: index("notif_type_idx").on(table.type),
    isReadIdx: index("notif_is_read_idx").on(table.isRead),
    createdAtIdx: index("notif_created_at_idx").on(table.createdAt),
  })
);

export type Notification = typeof notifications.$inferSelect;
export type InsertNotification = typeof notifications.$inferInsert;

/* ============================================================
   SECTION 11: ACHIEVEMENTS & GAMIFICATION
   ============================================================ */

/**
 * achievement_badges — Platform-wide badge definitions.
 * Awarded to talent for milestones and accomplishments.
 */
export const achievementBadges = mysqlTable(
  "achievement_badges",
  {
    id: serial("id").primaryKey(),
    slug: varchar("slug", { length: 100 }).notNull().unique(),
    name: varchar("name", { length: 255 }).notNull(),
    description: text("description"),
    category: mysqlEnum("category", [
      "wri_milestone",
      "crucible",
      "quickwork",
      "impact",
      "learning",
      "social",
      "special",
    ]).notNull(),
    tier: mysqlEnum("tier", ["bronze", "silver", "gold", "platinum"]).default("bronze").notNull(),
    iconUrl: varchar("icon_url", { length: 500 }),
    conditionType: varchar("condition_type", { length: 100 }).notNull(), // e.g. "wri_score_reached", "shifts_completed"
    conditionValue: varchar("condition_value", { length: 255 }), // e.g. "60", "5"
    pointsAwarded: int("points_awarded").default(0).notNull(),
    isActive: boolean("is_active").default(true).notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => ({
    slugIdx: index("badge_slug_idx").on(table.slug),
    categoryIdx: index("badge_category_idx").on(table.category),
  })
);

export type AchievementBadge = typeof achievementBadges.$inferSelect;
export type InsertAchievementBadge = typeof achievementBadges.$inferInsert;

/**
 * user_badges — Badge assignments to users.
 */
export const userBadges = mysqlTable(
  "user_badges",
  {
    id: serial("id").primaryKey(),
    userId: bigint("user_id", { mode: "number", unsigned: true }).notNull(),
    badgeId: bigint("badge_id", { mode: "number", unsigned: true }).notNull(),
    awardedAt: timestamp("awarded_at").defaultNow().notNull(),
    awardedBy: varchar("awarded_by", { length: 255 }), // "system" or trigger name
    contextData: text("context_data"), // JSON with details
  },
  (table) => ({
    userBadgeUniqueIdx: index("user_badge_unique_idx").on(table.userId, table.badgeId),
    userIdIdx: index("user_badge_user_id_idx").on(table.userId),
  })
);

export type UserBadge = typeof userBadges.$inferSelect;
export type InsertUserBadge = typeof userBadges.$inferInsert;

/* ============================================================
   SECTION 12: MESSAGING
   ============================================================ */

/**
 * conversations — Chat threads between users.
 */
export const conversations = mysqlTable(
  "conversations",
  {
    id: serial("id").primaryKey(),
    jobId: bigint("job_id", { mode: "number", unsigned: true }),
    shiftId: bigint("shift_id", { mode: "number", unsigned: true }),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
);

export type Conversation = typeof conversations.$inferSelect;
export type InsertConversation = typeof conversations.$inferInsert;

/**
 * conversation_participants — Links users to conversations.
 */
export const conversationParticipants = mysqlTable(
  "conversation_participants",
  {
    id: serial("id").primaryKey(),
    conversationId: bigint("conversation_id", { mode: "number", unsigned: true }).notNull(),
    userId: bigint("user_id", { mode: "number", unsigned: true }).notNull(),
    lastReadAt: timestamp("last_read_at"),
  },
  (table) => ({
    convUserIdx: uniqueIndex("conv_user_idx").on(table.conversationId, table.userId),
  })
);

export type ConversationParticipant = typeof conversationParticipants.$inferSelect;
export type InsertConversationParticipant = typeof conversationParticipants.$inferInsert;

/**
 * messages — Individual chat messages.
 */
export const messages = mysqlTable(
  "messages",
  {
    id: serial("id").primaryKey(),
    conversationId: bigint("conversation_id", { mode: "number", unsigned: true }).notNull(),
    senderId: bigint("sender_id", { mode: "number", unsigned: true }).notNull(),
    content: text("content").notNull(),
    isRead: boolean("is_read").default(false).notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => ({
    convIdx: index("msg_conv_idx").on(table.conversationId),
    createdIdx: index("msg_created_idx").on(table.createdAt),
  })
);

export type Message = typeof messages.$inferSelect;
export type InsertMessage = typeof messages.$inferInsert;

/* ============================================================
   SECTION 13: SOCIAL FEED
   ============================================================ */

/**
 * posts — Community feed posts (achievements, updates, peer shares).
 */
export const posts = mysqlTable(
  "posts",
  {
    id: serial("id").primaryKey(),
    profileId: bigint("profile_id", { mode: "number", unsigned: true }).notNull(),
    content: text("content").notNull(),
    postType: mysqlEnum("post_type", ["achievement", "milestone", "update", "peer_endorsement", "course_complete"])
      .default("update")
      .notNull(),
    relatedEntityId: bigint("related_entity_id", { mode: "number", unsigned: true }), // course, job, etc.
    likeCount: int("like_count").default(0).notNull(),
    commentCount: int("comment_count").default(0).notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => ({
    profileIdIdx: index("posts_profile_id_idx").on(table.profileId),
    typeIdx: index("posts_type_idx").on(table.postType),
    createdIdx: index("posts_created_idx").on(table.createdAt),
  })
);

export type Post = typeof posts.$inferSelect;
export type InsertPost = typeof posts.$inferInsert;

/**
 * post_likes — Like records on posts.
 */
export const postLikes = mysqlTable(
  "post_likes",
  {
    id: serial("id").primaryKey(),
    postId: bigint("post_id", { mode: "number", unsigned: true }).notNull(),
    profileId: bigint("profile_id", { mode: "number", unsigned: true }).notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => ({
    postProfileIdx: uniqueIndex("post_like_idx").on(table.postId, table.profileId),
  })
);

export type PostLike = typeof postLikes.$inferSelect;
export type InsertPostLike = typeof postLikes.$inferInsert;

/**
 * comments — Comments on feed posts.
 */
export const comments = mysqlTable(
  "comments",
  {
    id: serial("id").primaryKey(),
    postId: bigint("post_id", { mode: "number", unsigned: true }).notNull(),
    profileId: bigint("profile_id", { mode: "number", unsigned: true }).notNull(),
    content: text("content").notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => ({
    postIdIdx: index("comments_post_id_idx").on(table.postId),
  })
);

export type Comment = typeof comments.$inferSelect;
export type InsertComment = typeof comments.$inferInsert;

/* ============================================================
   SECTION 14: PAYMENTS (Mobile Money)
   ============================================================ */

/**
 * payment_transactions — MTN/Airtel mobile money transactions.
 * Status: pending → processing → completed | failed
 */
export const paymentTransactions = mysqlTable(
  "payment_transactions",
  {
    id: serial("id").primaryKey(),
    profileId: bigint("profile_id", { mode: "number", unsigned: true }).notNull(),
    transactionType: mysqlEnum("transaction_type", ["wallet_topup", "course_purchase", "withdrawal", "quickwork_payout"])
      .notNull(),
    provider: mysqlEnum("provider", ["mtn_momo", "airtel_money", "bank_transfer"]).notNull(),
    amountZmw: decimal("amount_zmw", { precision: 10, scale: 2 }).notNull(),
    externalReference: varchar("external_reference", { length: 255 }),
    status: mysqlEnum("status", ["pending", "processing", "completed", "failed"])
      .default("pending")
      .notNull(),
    phoneNumber: varchar("phone_number", { length: 20 }),
    description: text("description"),
    metadata: json("metadata"),
    completedAt: timestamp("completed_at"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => ({
    profileIdIdx: index("payments_profile_id_idx").on(table.profileId),
    statusIdx: index("payments_status_idx").on(table.status),
    externalRefIdx: index("payments_external_ref_idx").on(table.externalReference),
  })
);

export type PaymentTransaction = typeof paymentTransactions.$inferSelect;
export type InsertPaymentTransaction = typeof paymentTransactions.$inferInsert;

/* ============================================================
   SECTION 15: CERTIFICATES
   ============================================================ */

/**
 * certificates — Course completion certificates.
 */
export const certificates = mysqlTable(
  "certificates",
  {
    id: serial("id").primaryKey(),
    profileId: bigint("profile_id", { mode: "number", unsigned: true }).notNull(),
    courseId: bigint("course_id", { mode: "number", unsigned: true }).notNull(),
    certificateNumber: varchar("certificate_number", { length: 255 }).notNull().unique(),
    // e.g., "LEVAV-2026-0001"
    courseTitle: varchar("course_title", { length: 500 }).notNull(),
    instructorName: varchar("instructor_name", { length: 255 }),
    issueDate: timestamp("issue_date").defaultNow().notNull(),
    expiryDate: timestamp("expiry_date"),
    verificationUrl: text("verification_url"),
    isRevoked: boolean("is_revoked").default(false).notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => ({
    profileCourseIdx: uniqueIndex("cert_profile_course_idx").on(table.profileId, table.courseId),
    certNumberIdx: index("cert_number_idx").on(table.certificateNumber),
  })
);

export type Certificate = typeof certificates.$inferSelect;
export type InsertCertificate = typeof certificates.$inferInsert;


/* ============================================================
   SECTION 16: REFERRAL PROGRAM
   ============================================================ */

/**
 * referrals — Referral tracking (invite friends, earn rewards).
 */
export const referrals = mysqlTable(
  "referrals",
  {
    id: serial("id").primaryKey(),
    referrerProfileId: bigint("referrer_profile_id", { mode: "number", unsigned: true }).notNull(),
    referredProfileId: bigint("referred_profile_id", { mode: "number", unsigned: true }),
    referralCode: varchar("referral_code", { length: 20 }).notNull(),
    status: mysqlEnum("status", ["pending", "signed_up", "completed", "rewarded"])
      .default("pending")
      .notNull(),
    rewardAmountZmw: decimal("reward_amount_zmw", { precision: 8, scale: 2 }).default("5.00"),
    rewardedAt: timestamp("rewarded_at"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => ({
    codeIdx: uniqueIndex("referral_code_idx").on(table.referralCode),
    referrerIdx: index("referral_referrer_idx").on(table.referrerProfileId),
  })
);

export type Referral = typeof referrals.$inferSelect;
export type InsertReferral = typeof referrals.$inferInsert;

/* ============================================================
   SECTION 17: PUSH NOTIFICATION SUBSCRIPTIONS
   ============================================================ */

/**
 * push_subscriptions — Browser push notification subscriptions.
 */
export const pushSubscriptions = mysqlTable(
  "push_subscriptions",
  {
    id: serial("id").primaryKey(),
    userId: bigint("user_id", { mode: "number", unsigned: true }).notNull(),
    endpoint: varchar("endpoint", { length: 500 }).notNull(),
    p256dh: varchar("p256dh", { length: 255 }).notNull(),
    auth: varchar("auth_key", { length: 255 }).notNull(),
    // Notification preferences (stored as JSON)
    preferences: json("preferences").$type<{
      jobAlerts: boolean;
      messages: boolean;
      wriUpdates: boolean;
      courseUpdates: boolean;
      systemAnnouncements: boolean;
    }>(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => ({
    userIdx: index("push_sub_user_idx").on(table.userId),
    endpointIdx: uniqueIndex("push_sub_endpoint_idx").on(table.endpoint),
  })
);

export type PushSubscription = typeof pushSubscriptions.$inferSelect;
export type InsertPushSubscription = typeof pushSubscriptions.$inferInsert;

/* ============================================================
   SECTION 18: INTERVIEWS
   ============================================================ */

/**
 * interviews — Scheduled interviews between employers and talent.
 */
export const interviews = mysqlTable(
  "interviews",
  {
    id: serial("id").primaryKey(),
    applicationId: bigint("application_id", { mode: "number", unsigned: true }).notNull(),
    employerProfileId: bigint("employer_profile_id", { mode: "number", unsigned: true }).notNull(),
    talentProfileId: bigint("talent_profile_id", { mode: "number", unsigned: true }).notNull(),
    scheduledAt: timestamp("scheduled_at").notNull(),
    durationMinutes: int("duration_minutes").default(30).notNull(),
    meetingLink: text("meeting_link"),
    interviewType: mysqlEnum("interview_type", ["video", "audio", "in_person"])
      .default("video")
      .notNull(),
    status: mysqlEnum("status", ["scheduled", "confirmed", "completed", "cancelled", "no_show"])
      .default("scheduled")
      .notNull(),
    employerNotes: text("employer_notes"),
    talentNotes: text("talent_notes"),
    reminderSent: boolean("reminder_sent").default(false).notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => ({
    applicationIdx: index("interview_app_idx").on(table.applicationId),
    employerIdx: index("interview_employer_idx").on(table.employerProfileId),
    talentIdx: index("interview_talent_idx").on(table.talentProfileId),
    scheduledIdx: index("interview_scheduled_idx").on(table.scheduledAt),
  })
);

export type Interview = typeof interviews.$inferSelect;
export type InsertInterview = typeof interviews.$inferInsert;
/* ============================================================
   SECTION 19: EMAIL VERIFICATION
   ============================================================ */

export const emailVerificationCodes = mysqlTable(
  "email_verification_codes",
  {
    id: serial("id").primaryKey(),
    userId: bigint("user_id", { mode: "number", unsigned: true }).notNull(),
    code: varchar("code", { length: 6 }).notNull(),
    expiresAt: timestamp("expires_at").notNull(),
    used: boolean("used").default(false).notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => ({
    userIdx: index("evc_user_idx").on(table.userId),
    codeIdx: index("evc_code_idx").on(table.code),
  })
);

export type EmailVerificationCode = typeof emailVerificationCodes.$inferSelect;
export type InsertEmailVerificationCode = typeof emailVerificationCodes.$inferInsert;

/* ============================================================
   SECTION 20: PASSWORD RESET TOKENS
   ============================================================ */

export const passwordResetTokens = mysqlTable(
  "password_reset_tokens",
  {
    id: serial("id").primaryKey(),
    userId: bigint("user_id", { mode: "number", unsigned: true }).notNull(),
    token: varchar("token", { length: 64 }).notNull(),
    expiresAt: timestamp("expires_at").notNull(),
    used: boolean("used").default(false).notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => ({
    tokenIdx: uniqueIndex("prt_token_idx").on(table.token),
    userIdx: index("prt_user_idx").on(table.userId),
  })
);

export type PasswordResetToken = typeof passwordResetTokens.$inferSelect;

/* ============================================================
   SECTION 21: CHAMPION APPLICATIONS
   ============================================================ */

export const championApplications = mysqlTable(
  "champion_applications",
  {
    id: serial("id").primaryKey(),
    firstName: varchar("first_name", { length: 255 }).notNull(),
    lastName: varchar("last_name", { length: 255 }).notNull(),
    email: varchar("email", { length: 255 }).notNull(),
    phone: varchar("phone", { length: 50 }),
    city: varchar("city", { length: 100 }).notNull(),
    profession: varchar("profession", { length: 255 }).notNull(),
    role: varchar("role", { length: 255 }).notNull(),
    experience: varchar("experience", { length: 50 }),
    wriScore: decimal("wri_score", { precision: 5, scale: 2 }).default("0"),
    goldKeyTier: varchar("gold_key_tier", { length: 50 }),
    levavCode: varchar("levav_code", { length: 50 }),
    expertiseAreas: json("expertise_areas").$type<string[]>(),
    mentorshipStyle: varchar("mentorship_style", { length: 50 }),
    availability: varchar("availability", { length: 50 }),
    motivation: text("motivation"),
    contentInterest: boolean("content_interest").default(false),
    linkedinUrl: varchar("linkedin_url", { length: 500 }),
    portfolioUrl: varchar("portfolio_url", { length: 500 }),
    status: mysqlEnum("status", ["pending", "approved", "rejected"]).default("pending").notNull(),
    appliedAt: timestamp("applied_at").defaultNow().notNull(),
    reviewedAt: timestamp("reviewed_at"),
    honorariumRate: int("honorarium_rate").default(0),
    totalEarnings: int("total_earnings").default(0),
    menteesCount: int("mentees_count").default(0),
    sessionsCompleted: int("sessions_completed").default(0),
    contentPublished: int("content_published").default(0),
  },
  (table) => ({
    emailIdx: uniqueIndex("champ_email_idx").on(table.email),
    statusIdx: index("champ_status_idx").on(table.status),
  })
);

export type ChampionApplication = typeof championApplications.$inferSelect;

/* ============================================================
   SECTION 22: CREATOR APPLICATIONS
   ============================================================ */

export const creatorApplications = mysqlTable(
  "creator_applications",
  {
    id: serial("id").primaryKey(),
    firstName: varchar("first_name", { length: 255 }).notNull(),
    lastName: varchar("last_name", { length: 255 }).notNull(),
    email: varchar("email", { length: 255 }).notNull(),
    phone: varchar("phone", { length: 50 }),
    city: varchar("city", { length: 100 }),
    profession: varchar("profession", { length: 255 }),
    role: varchar("role", { length: 255 }),
    contentTypes: json("content_types").$type<string[]>(),
    categories: json("categories").$type<string[]>(),
    bio: text("bio"),
    sampleUrl: varchar("sample_url", { length: 500 }),
    equipment: varchar("equipment", { length: 50 }),
    postingFrequency: varchar("posting_frequency", { length: 50 }),
    monetizationInterest: boolean("monetization_interest").default(true),
    status: mysqlEnum("status", ["pending", "approved", "rejected"]).default("pending").notNull(),
    appliedAt: timestamp("applied_at").defaultNow().notNull(),
    reviewedAt: timestamp("reviewed_at"),
    totalContent: int("total_content").default(0),
    totalViews: int("total_views").default(0),
    totalEarnings: int("total_earnings").default(0),
  },
  (table) => ({
    emailIdx: uniqueIndex("creator_email_idx").on(table.email),
    statusIdx: index("creator_status_idx").on(table.status),
  })
);

export type CreatorApplication = typeof creatorApplications.$inferSelect;
export type InsertPasswordResetToken = typeof passwordResetTokens.$inferInsert;
